<?php

/**
 * @file
 * Preprocess functions for Stanford Starter.
 */

/**
 * Prepares variables for the html.html.twig template.
 */
function lbretransportation_subtheme_preprocess_html(&$variables) {
  $variables['stanford_basic_path'] = \Drupal::service('extension.list.theme')
    ->getPath('stanford_basic');
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function lbretransportation_subtheme_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  if (!empty($variables['elements']['#id']) && $variables['elements']['#id'] == 'lbretransportation_subtheme_search') {
    $suggestions[] = 'block__stanford_basic_search';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function lbretransportation_subtheme_preprocess_paragraph__stanford_banner(&$variables) {
  /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
  $paragraph = $variables['paragraph'];

  $variables['attributes']['class'][] = $paragraph->getBehaviorSetting('react_paragraphs:banner_style', 'layout', 'layout--default');
  $variables['attributes']['class'][] = $paragraph->getBehaviorSetting('react_paragraphs:banner_style', 'color_scheme', 'color--cardinal-red');
  $variables['#attached']['library'][] = 'lbretransportation_subtheme/hero-js';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function lbretransportation_subtheme_preprocess_paragraph__stanford_lists(array &$variables): void {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];
  $variables['attributes']['class'][] = $paragraph->getBehaviorSetting('react_paragraphs:lists_style', 'cards_color', 'cards-color--light');
}

/**
 * Implements hook_preprocess_HOOK().
 */
function lbretransportation_subtheme_preprocess_paragraph__stanford_wysiwyg(array &$variables): void {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];
  $variables['attributes']['class'][] = $paragraph->getBehaviorSetting('react_paragraphs:wysiwyg_style', 'style', 'style--default');
  $variables['attributes']['class'][] = $paragraph->getBehaviorSetting('react_paragraphs:wysiwyg_style', 'color_scheme', 'color--default');
}

/**
 * Implements hook_preprocess_HOOK().
 */
function lbretransportation_subtheme_preprocess_node__stanford_page__stanford_h3_card(&$variables) {
  $node = $variables['node'];
  [$color, $tag] = check_shuttle_title($node->label());
  $variables['flag_color'] = $color;
  $variables['tag'] = $tag;
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function lbretransportation_subtheme_theme_suggestions_node_alter(array &$suggestions, array &$variables) {
  /** @var \Drupal\node\NodeInterface $node */
  $node = $variables['elements']['#node'];
  $view_mode = $variables['elements']['#view_mode'];
  if (
    $node->bundle() != 'stanford_page' ||
    !in_array($view_mode, ['stanford_card', 'stanford_h3_card'])
  ) {
    return;
  }

  if (
    $node->hasField('su_shared_tags') &&
    $node->get('su_shared_tags')->count()
  ) {
    $is_shuttle = !!array_filter($node->get('su_shared_tags')
      ->getValue(), fn($val) => $val['target_id'] == 406);

    if ($is_shuttle) {
      $suggestions[] = "node__stanford_page__{$view_mode}__shuttle";
    }
  }
}

/*
  Function check title string.
  Returns theme color as string and flag content as string.
 */
function check_shuttle_title($title) {
  $card_theme = "";
  $card_theme_label = "";
  switch ($title) {
    case "1050 Arastradero":
      $card_theme = 'brown';
      $card_theme_label = t('1050 A');
      break;
    case "Line RWC":
      $card_theme = 'light-red';
      $card_theme_label = t('RWC');
      break;
    case "Line AE-F":
      $card_theme = 'gray';
      $card_theme_label = t('AE-F');
      break;
    case "Line C":
      $card_theme = 'cyan';
      $card_theme_label = t('C');
      break;
    case "East Bay Express":
      $card_theme = 'blue';
      $card_theme_label = t('EB');
      break;
    case "Hospital: Direct":
      $card_theme = 'blue-green';
      $card_theme_label = t('HD');
      break;
    case "Medical Center":
      $card_theme = 'violet';
      $card_theme_label = t('MC');
      break;
    case "Oak Creek Apartments":
      $card_theme = 'dark-gray';
      $card_theme_label = t('OCA');
      break;
    case "Line P":
      $card_theme = 'light-green';
      $card_theme_label = t('P');
      break;
    case "Research Park":
      $card_theme = 'dark-green';
      $card_theme_label = t('RP');
      break;
    case "Line S":
      $card_theme = 'brown-green';
      $card_theme_label = t('S');
      break;
    case "Shopping Express":
      $card_theme = 'pink';
      $card_theme_label = t('SE');
      break;
    case "SLAC":
      $card_theme = 'green';
      $card_theme_label = t('SLAC');
      break;
    case "Line X (Counter-Clockwise)":
      $card_theme = 'red';
      $card_theme_label = t('X');
      break;
    case "Line Y (Clockwise)":
      $card_theme = 'red';
      $card_theme_label = t('Y');
      break;
    case "CAX Line":
      $card_theme = 'bright-yellow';
      $card_theme_label = t('CAX');
      break;
    default:
      break;
  }

  return [$card_theme, $card_theme_label];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function lbretransportation_subtheme_preprocess_field__node__title(&$variables) {
  $node = $variables['element']['#object'];

  if ($node->bundle() == 'stanford_page' && $node->hasField('su_shared_tags')) {
    $is_shuttle_route = in_array('406', array_map(function($value) {
      return $value['target_id'];
    }, $node->su_shared_tags->getValue()));

    if ($is_shuttle_route) {
      $card_theme = check_shuttle_title($node->label());

      $variables['items'][0]['content']['#suffix'] = '<span class="flag-mark--after flag-mark--' . $card_theme[0] . '" style="--flag-mark-content: ' . "'" . $card_theme[1] . "'" . '"></span>';

      $variables['attributes']['class'][] = 'title-with-flag';
    }
  }
}
